"""update worker category

Revision ID: 28bc4fa59a4d
Revises: 4540de37bc03
Create Date: 2015-03-14 20:46:14.599094

"""

# revision identifiers, used by Alembic.
revision = '28bc4fa59a4d'
down_revision = '4540de37bc03'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_worker_category_id'), ['category_id'], unique=False)
        batch_op.drop_index('ix_worker_username')
    op.execute('update worker set category_id=(select category_id from worker_category where worker_category.worker_id=worker.id);')
    #op.drop_table('worker_category')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_category',
    sa.Column('worker_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('category_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('created_time', mysql.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('worker_id', 'category_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.create_index('ix_worker_username', ['username'], unique=False)
        batch_op.drop_index('ix_worker_category_id')
        batch_op.drop_column('category_id')
    ### end Alembic commands ###
