"""delete index

Revision ID: 444b8049ddbf
Revises: 28bc4fa59a4d
Create Date: 2015-03-15 16:07:15.076683

"""

# revision identifiers, used by Alembic.
revision = '444b8049ddbf'
down_revision = '28bc4fa59a4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_sort_score')
        batch_op.create_index(batch_op.f('ix_category_sort_score'), ['sort_score'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index('ix_media_worker_id')
        batch_op.create_index(batch_op.f('ix_media_id'), ['id'], unique=False)

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_username'), ['username'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_username'))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_id'))
        batch_op.create_index(batch_op.f('ix_media_worker_id'), ['worker_id'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_sort_score'))
        batch_op.create_index('ix_category_sort_score', ['key'], unique=False)

    ### end Alembic commands ###
