"""init_tables

Revision ID: 4237a3acb4e2
Revises: None
Create Date: 2014-12-07 15:07:46.599371

"""

# revision identifiers, used by Alembic.
revision = '4237a3acb4e2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.String(length=128), server_default='704f9a2107b1', autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admin_created_time'), 'admin', ['created_time'], unique=False)
    op.create_index('ix_admin_email_password', 'admin', ['email', 'password'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=128), server_default='704f9a2107b1', autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_time'), 'user', ['created_time'], unique=False)
    op.create_table('media',
    sa.Column('mid', sa.String(length=128), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('low_resolution', sa.String(length=256), nullable=False),
    sa.Column('thumbnail', sa.String(length=256), nullable=False),
    sa.Column('standard_resolution', sa.String(length=256), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_index(op.f('ix_media_created_time'), 'media', ['created_time'], unique=False)
    op.create_index(op.f('ix_media_updated_time'), 'media', ['updated_time'], unique=False)
    op.create_index(op.f('ix_media_worker_id'), 'media', ['worker_id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.String(length=128), server_default='704f9a2107b1', autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_created_time'), 'category', ['created_time'], unique=False)
    op.create_index(op.f('ix_category_key'), 'category', ['key'], unique=False)
    op.create_table('woker',
    sa.Column('id', sa.String(length=128), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_woker_created_time'), 'woker', ['created_time'], unique=False)
    op.create_index(op.f('ix_woker_updated_time'), 'woker', ['updated_time'], unique=False)
    op.create_index(op.f('ix_woker_user_name'), 'woker', ['user_name'], unique=False)
    op.create_table('woker_category',
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.String(length=128), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('worker_id', 'category_id')
    )
    op.create_index(op.f('ix_woker_category_created_time'), 'woker_category', ['created_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_woker_category_created_time'), table_name='woker_category')
    op.drop_table('woker_category')
    op.drop_index(op.f('ix_woker_user_name'), table_name='woker')
    op.drop_index(op.f('ix_woker_updated_time'), table_name='woker')
    op.drop_index(op.f('ix_woker_created_time'), table_name='woker')
    op.drop_table('woker')
    op.drop_index(op.f('ix_category_key'), table_name='category')
    op.drop_index(op.f('ix_category_created_time'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_media_worker_id'), table_name='media')
    op.drop_index(op.f('ix_media_updated_time'), table_name='media')
    op.drop_index(op.f('ix_media_created_time'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_user_created_time'), table_name='user')
    op.drop_table('user')
    op.drop_index('ix_admin_email_password', table_name='admin')
    op.drop_index(op.f('ix_admin_created_time'), table_name='admin')
    op.drop_table('admin')
    ### end Alembic commands ###
